### ISSUE TITLE
[Need Help]请问默认账密是什么？

### ISSUE THREAD

**Issue by OcrSu** [Carseason/openwrt-mfun#2]

**Comment by Carseason** [comment]
admin password
忘记在插件写上了，一会更新一下

**Comment by OcrSu** [comment]
> admin password 忘记在插件写上了，一会更新一下

已经登录上了，我用iStoreOS安装的，第一次用edge浏览器登录admin账户后台后，界面上有些地方选项框内容显示不出来，切换一次白天黑夜模式就正常了。

**Comment by Carseason** [comment]
这个后面会更新的哈
